### ISSUE TITLE
[Invalid] 방어구 이름이 서버와 클라가 다름

### ISSUE THREAD

**Issue by rabbitmjh** [Charge-Evolution-Battle-on-Earth/Server#49]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/d846eb0c-6835-4d6b-a9e2-b37073e05e0e)
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/442fe179-4884-4e07-92db-3f702808d067)

서버에서 가지고 있는 방어구의 이름과 다른 것들이 존재

서버에만 있는 것: 체인메일, 어린갑
클라에만 있는 것: 크럭흉갑, 미늘갑

[미늘갑]
![미늘갑](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/9e28ace0-793f-4ebe-bcc9-4dffa49ae584)
[크럭흉갑]
![크럭흉갑](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/0b45fc40-dde2-4086-8c2c-6c90181cc94e)

체인메일이랑 어린갑을 검색해보니까 미늘갑이나 크럭흉갑이랑 다른 거 같아서
이미지가 안 맞는듯

**Comment by duddn2012** [comment]
Database 데이터 수정 완료
