### ISSUE TITLE
[Bug] Quit API 응답 오류

### ISSUE THREAD

**Issue by rabbitmjh** [Charge-Evolution-Battle-on-Earth/Server#53]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/c9f3e479-9711-4ee8-a445-c422c425ede1)

1이 host
2가 entrant

2가 들어왔다 나가면서 Quit 요청을 보내는데
아직 방에 남아있는 1에게 빈 값이 옴.

**Comment by duddn2012** [comment]
#55 START 와 Quit API 외 WebSocket Ingame API 모두 응답 Message 반환하도록 수정
