### ISSUE TITLE
웹소켓 메시지 길이 제한 초과 오류

### ISSUE THREAD

**Issue by rabbitmjh** [Charge-Evolution-Battle-on-Earth/Server#78]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/1fb01294-59f7-4cab-8a60-20da14a59246)
게임 시작 버튼을 누르면 이런 오류 메시지가 발생

![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/b9d369ea-55d6-4e97-ae4e-8e59e52aa2b3)
서버에서 온 메시지는 700자에서 끊겨
클라이언트에서 JSON 파싱이 불가능해 뜨는 오류로 추정됨

**Comment by duddn2012** [comment]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/31121731/0bbbd48c-754c-43c2-8be6-c59dd6ec4302)

POSTMAN 테스트 결과 700자 이상 메세지에 대해 정상적으로 응답을 받음.
프론트에서 메세지 받는 부분과 파싱 부분 확인해봐야 할 듯.

**Comment by rabbitmjh** [comment]
https://github.com/Charge-Evolution-Battle-on-Earth/Client/pull/44/commits/39af7b79b88d736db9b2d8c89847869c3f755b39

버퍼 사이즈를 10배 늘렸더니 정상적으로 받아짐
