### ISSUE TITLE
Ready API host로 요청을 보내도 변경이 안되는 오류

### ISSUE THREAD

**Issue by rabbitmjh** [Charge-Evolution-Battle-on-Earth/Server#87]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/4dc76f77-3941-43a8-9539-128dc42b4d86)

클라이언트에서 Ready 버튼을 누를 때 조건은 다음과 같음.
```C#
if(UserDataManager.Instance.UserId == UserDataManager.Instance.HostId)
{
     requestData.request.hostReadyStatus = !UserDataManager.Instance.HostReady;
     requestData.request.entrantReadyStatus =  UserDataManager.Instance.EntrantReady;
}
else if(UserDataManager.Instance.UserId == UserDataManager.Instance.EntrantId)
{
     requestData.request.hostReadyStatus = UserDataManager.Instance.HostReady;
     requestData.request.entrantReadyStatus = !UserDataManager.Instance.EntrantReady;
}
````

**Comment by duddn2012** [comment]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/31121731/00658e16-1ff3-4e37-9205-2ae9ea8491a7)

API 테스트 결과 정상적으로 처리되고 있음.
프론트 코드 확인해봐야 할 듯.

**Comment by rabbitmjh** [comment]
[처리완료](https://github.com/Charge-Evolution-Battle-on-Earth/Client/pull/48/commits/27c1efb6b1d49d4219e9590f6741edf8b732f2ee)
