### ISSUE TITLE
[Feat] 타이머가 0이 됐을 때 턴 스킵 방법

### ISSUE THREAD

**Issue by rabbitmjh** [Charge-Evolution-Battle-on-Earth/Server#94]
![image](https://github.com/Charge-Evolution-Battle-on-Earth/Server/assets/110733523/95567fe5-8ddc-4e78-938a-7cf1a5962cbd)
클라이언트에서 skillId를 0으로 보냈을 때 턴이 스킵되는 방식
skillId 0번 스킬은 데미지 0, MP 소모 0으로 게임에는 영향이 안가도록함.

**Comment by duddn2012** [comment]
타이머 0이 되었을 때  클라이언트에서 기본 공격에 대한 스킬 ID를 보내는 것으로 처리
